# Generated by Django 2.2 on 2020-03-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
