# Generated by Django 2.2 on 2020-03-23 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0003_auto_20200323_2228'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Return',
        ),
    ]
